// vue3/src/SubPage.vue
<template>
  <div>
    <button
      class="button"
      @click="start"
    >开始</button>

    <div>text: {{ wtf }}</div>
  </div>
</template>

<script>
  export default {
    name: 'app',
    props: {},
    data() {
      return {
        wtf: 11,
        list: [],
        timer: null,
      }
    },
    created() {
      const list = []
      for (let i = 0; i < 10000; i++) {
        list.push({
          label: 'Item ' + i,
          value: i,
        })
      }
      this.list = list
    },
    unmounted() {
      // 对比使用这个跟不使用的区别
      // clearTimeout(this.timer)
    },
    methods: {
      start() {
        console.log('start')
        this.timer = setTimeout(() => {
          console.log(this)
          this.wtf += 99
        }, 2000)
      },
    },
  }
</script>

// react/src/SubPage.jsx
import React, { useEffect } from 'react'

const init = () => {
  const list = []
  for (let i = 0; i < 100000; i++) {
    list.push({
      label: 'Item ' + i,
      value: i
    })
  }
  return list
}

export default () => {
  const [list, setList] = React.useState(init())
  useEffect(() => {
    const timer = setTimeout(() => {
      console.log(list)
    }, 3000)
    return () => {
      // 对比这里
      clearTimeout(timer)
    }
  }, [])
  return <div>sub component</div>
}
